### ISSUE TITLE
Chansey

### ISSUE THREAD

**Issue by khaldresh** [RichardPaulAstley/richardpaulastley.github.io#10]
Chanseys Base stats are extremely low  are they supposed to be at about 360 lvl 100?

**Comment by khaldresh** [comment]
(btw  finally got all pokemon IN ORDER)  at least highest evolution of each        now i gotta get them to lvl 100 :D

**Comment by khaldresh** [comment]
366 ATD  366 DEF   is a bit low    (it's 100 now)

**Comment by khaldresh** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/26366691/23836981/01dd8624-0781-11e7-8e5b-cfed68cdb3d4.JPG)

**Comment by RichardPaulAstley** [comment]
Congratulations haha ! 
I hope you'll be able to wait for the next gens, really busy to do all properly.

So ! For Chansey I GUESS i got it. Working on a offline version because I'm too bad for editing this and I guess i'll break everything sadly :/

**Comment by RichardPaulAstley** [comment]
I confirm. The game is ONLY taking advantage of Attack and Defense. Special stats are just ignored.
Gonna try to fix that, and put a .6

**Comment by RichardPaulAstley** [comment]
![image](https://cloud.githubusercontent.com/assets/25870563/23837110/759c241a-0783-11e7-867a-7ccd2232e4ad.png)
I'm the first surprised. Gonna put that online. Tell me if it works !

**Comment by khaldresh** [comment]
yah not done yet   will let my new kangaskhan  lvl up to 100 over night   and then i'll go on XD    caught them now just need to lvl them    will post screens (in a new post maybe) when done :D

**Comment by RichardPaulAstley** [comment]
I'm thinking about making a subreddit for the game itself in the future. For talking about updates and etc in public. So, it'll help you haha !

For the moment just tell me if your Chansey is better than before.

**Comment by khaldresh** [comment]
ATK 1366
DEF 3699.5
still the lowest stats by far :D  ever butterfree @ 100 hast 4,5k 4,5k  same with dugtrio

**Comment by RichardPaulAstley** [comment]
Yep, but this time it's the Pokemon itself, not related to a fail from the game. 
![image](https://cloud.githubusercontent.com/assets/25870563/23837263/b23cc2b0-0785-11e7-88ad-834d0680b1ac.png)
Chansey is just good in HP.

Check for Butterfree 
![image](https://cloud.githubusercontent.com/assets/25870563/23837273/d7708c4c-0785-11e7-9e01-c8c9079958a5.png)

It's just logic now.
300 was TOO low, but 3700 in Def just shows me that's working fine.

**Comment by khaldresh** [comment]
crappy pokemon then :D   as i had to get the others after kangaskhan  after herself to keep the order  i'll update you when i find sth :D   cloyster has a nice 10k defense btw :+1

**Comment by RichardPaulAstley** [comment]
Nice to see it's working fine ! 
I thought i'd break everything haha !

And good luck ! Gonna update with a subreddit once i'll have a name in mind
