### ISSUE TITLE
Game too Short   

### ISSUE THREAD

**Issue by khaldresh** [RichardPaulAstley/richardpaulastley.github.io#11]
You wanted to get informed:  
![unbenannt](https://cloud.githubusercontent.com/assets/26366691/23850211/b66f7a2c-07de-11e7-992c-c809da42f552.JPG)

![unbenannt2](https://cloud.githubusercontent.com/assets/26366691/23850168/9357e79a-07de-11e7-9c59-194399297861.JPG)
![unbenannt3](https://cloud.githubusercontent.com/assets/26366691/23850169/94be7fe0-07de-11e7-980b-63e9de744a29.JPG)
![unbenannt4](https://cloud.githubusercontent.com/assets/26366691/23850173/963d3a6e-07de-11e7-8b08-d5b80bf9cae8.JPG)

**Comment by RichardPaulAstley** [comment]
Not really an issue but congratulations.

Some updates are coming. Like the possibility to choose to evolve or not the Pokemon. This way, you'll have the 151 to farm and not simply the final evolutions. After Megas Pokemon will come with that, and the next gens etc too.

Just a game i'm WIP on it, i've already did many things about fixing bug and making the game playable (i mean being able to do what you've done)

**Comment by khaldresh** [comment]
Eew megas    that's the reason i stopped playing the editions   as megas ... dunno...  and 2 gens later there will be super-megas  and then we're at digimon again...

**Comment by RichardPaulAstley** [comment]
It'll be optional that's why they are not here for the moment. But if I want a Pokémon game for everybody, I need to put the more stuff as possible, to be close as real games.

But you'll be able to ignore them.
