### ISSUE TITLE
About Types

### ISSUE THREAD

**Issue by piiih** [RichardPaulAstley/richardpaulastley.github.io#12]
I saw the commit that you fixed the types, but I think there are some mistakes. Examples: Ice taking .5 damage from Fire and 2 for Flying and Ground.

Here is a table of the elements: https://pokemondb.net/type/dual

**Comment by RichardPaulAstley** [comment]
Hi !

Nop, you got it wrong !
The tabs show the move type, so Ice hits .5 on Fire.
and so super effective against Flying and Ground simply.

**Comment by piiih** [comment]
Yep, I just saw now that, I though that the type's number was the multiplier for damage taken. Sorry ;)
