### ISSUE TITLE
First! button

### ISSUE THREAD

**Issue by piiih** [RichardPaulAstley/richardpaulastley.github.io#15]
When change pokemon, the pokemon who take damage is the pokemon before the change.

**Comment by RichardPaulAstley** [comment]
I saw that too, but i've to talk to you about this, I had a nice idea for this and other stuff.

**Comment by piiih** [comment]
Nice! I would commit a quick fix about this, but we can talk first and then I fix this. When can we talk?

**Comment by RichardPaulAstley** [comment]
When you want ! I'm available for the next... 9 hours !

**Comment by piiih** [comment]
Ok, when I come home I'll notify you

**Comment by RichardPaulAstley** [comment]
No problem ! Because I think I've found the way to have everything more properly for the looks + With 2/3 ideas to do it way better.

Thanks !

**Comment by RichardPaulAstley** [comment]
The magane team will have a huge revamp so I guess it'll be fixed
