### ISSUE TITLE
Evee Evolution

### ISSUE THREAD

**Issue by DariunHetharto** [RichardPaulAstley/richardpaulastley.github.io#2]
Just wanted to leave you a note, the Evee evolution only works for Flareon. Further the lowest level you can catch and Evee is 25, so they won't be able to level up to 25 to evolve for the first of the three. I tested it a few times, catching a bunch of level 25, they only evolve to Flareon when they hit level 29. Hope this helps.

**Comment by RichardPaulAstley** [comment]
Hi !

I know this bug, i'm looking for a solution, because the game was coded for ONE evolution. I've tried to put evolutions at level 25/27/29 (this way you catch the right Evoli at the level you want the Eeveelution) but not sure it's working.

I'll add an Area with the evolutions may be before finding a REAL fix.

Thanks !

**Comment by RichardPaulAstley** [comment]
I've added them. Tell me if it's working fine on your end !

**Comment by DariunHetharto** [comment]
I can see vaporeon, jolteon and flareon now in celadon city. It is a good solution for now. If you plan to add items to the game that could work. Or create three different versions of evee, use the same icon but change their ID and it becomes random chance for wich eeveelution you get.

**Comment by RichardPaulAstley** [comment]
Well, i'll need some help or to learn how to do it before, but my plan is to let the player choose when the Pokemon can evolve (this way if I add Shiny later, people will have the control of what they have in their teams) 

So, for the moment, I guess it'll do the job !

Thanks for the head up, it was something I wanted to have feedback !
