### ISSUE TITLE
Redundant unlocked property of routes?

### ISSUE THREAD

**Issue by Ishadijcks** [RichardPaulAstley/richardpaulastley.github.io#31]
`<route>.unlocked` is always set to true, and is used twice in an `&&` condition. It appears this property can be removed from routes.js

**Comment by RichardPaulAstley** [comment]
Well, for this one, it's quite special. The function is working well, when you set the unlocked to false in the routes.js, well you can't access it at all.

I kept it for some reasons like future events, or making a progressing system (for legendary especially) so I've thought to delete it, but i guess it's not taking too much ressource on this one

**Comment by spark942** [comment]
you can remove the `unlocked: true`, and add a `event : 'eventname'` + in the code you do something like this :  

events.js
```javascript
const CURRENTEVENTS = ['M-Mewtwo X']
```

main.js
```javascript
const route = routes[routeId]
const unlocked = true
if (route.hasOwnProperty('event') && CURRENTEVENTS.indexOf(route.event) == -1)
  unlocked = false
setValue(...)
```

**Comment by RichardPaulAstley** [comment]
Gonna try that, didn't see it sorry x_x
Will see if nice to do or not for the future o/
