### ISSUE TITLE
Propose easier way to manage pokedex

### ISSUE THREAD

**Issue by spark942** [RichardPaulAstley/richardpaulastley.github.io#38]
Having a double digit flag
```
1 = Normal Seen
2 = Normal Released
3 = Normal Owned
10 = Shiny Seen
20 = Shiny Released
30 = Shiny Owned
```
Examples : 
Normal Owned : `3`
Shiny Seen & Normal Owned : `13`
Normal Released & Shiny Owned : `32`
Shiny Owned : `30`
Shiny Owned & Normal Seen : `31`

For the filters
Missing Living Mode : Show `3#` then `#3`|`3`
Missing Living + Had Mode :  `3#` then `#3`|`3`, `2#`, `#2`|`2`

**Comment by spark942** [comment]
This way, when dealing with normal, only changing last digit

**Comment by RichardPaulAstley** [comment]
Well, i'll see with racken the thing he wants, but it could be a good solution, thank you for the help once again !

**Comment by RichardPaulAstley** [comment]
Well this will be retalked about in a few days, closing that for the moment o7
