### ISSUE TITLE
Pokedex doesn't load on refresh

### ISSUE THREAD

**Issue by DanielMReed** [RichardPaulAstley/richardpaulastley.github.io#41]
If you have the pokedex open when you refresh, the left side is blank and you have to close the dex then reopen it.

**Comment by RichardPaulAstley** [comment]
Yep, it's a bug I'm aware of but really too much minors, i've other things to deal with it for the moment, sorry.

Thanks o/

**Comment by RichardPaulAstley** [comment]
Fixed, it resets to the Team management.
