### ISSUE TITLE
Team Management

### ISSUE THREAD

**Issue by MatheusVellone** [RichardPaulAstley/richardpaulastley.github.io#43]
The actual team management is simple but hard to deal with.
What if we could drag and drop pokemons to manage their order ? IMO this would be a lot easier.

I would love work on this update if you agree, but this can be a challenge for me

**Comment by RichardPaulAstley** [comment]
Hi, 

so First Button will come back next week-end if I mange the time to (from an old PR) some little things will be updated to make the Manage Team even better. 

You can try, but I think Drag & Drop will require a lot of things to do.

The game is open for that anyway 

Thanks o/
