### ISSUE TITLE
Ordering is ignored for new pokemon

### ISSUE THREAD

**Issue by renlok** [RichardPaulAstley/richardpaulastley.github.io#45]
new pokemon are added to the bottom of the list regardless of the ordering

**Comment by RichardPaulAstley** [comment]
Yep, but this is a thing wanted this time, this way people can check their new Pokemon easily, no issue on this one really a choice o/

**Comment by DanielMReed** [comment]
I have to agree with renlok, there at least needs to be a "auto sort" option

**Comment by renlok** [comment]
Then would it be a good idea to add a sort by newest

**Comment by DanielMReed** [comment]
I think just a simple "Auto" tick box next to the sort type that will sort the list again on capture?
