### ISSUE TITLE
Evolving Shiny doesn't remove old shiny from caught list

### ISSUE THREAD

**Issue by DanielMReed** [RichardPaulAstley/richardpaulastley.github.io#47]
If a Pokemon is evolved then the previous pokemon is not removed from the shiny list, meaning under missing the pokemon isn't listed. This then stops the "new catch only" from catching this pokemon. A pokedex option for "living" or "current caught" would solve this

**Comment by RichardPaulAstley** [comment]
It's aware, racken has the new version in mind, we're working on it, in order to release a fix before next week, if everything goes well o/

Thanks o/
