### ISSUE TITLE
Pokedex ideas

### ISSUE THREAD

**Issue by renlok** [RichardPaulAstley/richardpaulastley.github.io#49]
Backend flags:
0 Unseen
1 Normal, Seen
2 Shiny, Seen
3 Normal, Released [italic]
4 Shiny, Released [italic]
5 Normal, Owned (so evolved)
6 Normal, Own  (actual form in the team)
7 Shiny, Owned
8 Shiny, Own
How flags can change: #35 

Ordering:
- Add second dropbox to show only pokemon from certain areas

Features:
- Show where they can be found/evolution details (Not sure how to best display this info though without it looking messy)

**Comment by RichardPaulAstley** [comment]
Well, seems you used my order, so nothing else to say, let's go for that it'll work way better I think.

For the feature / ordering ones... Not sure if it's a good thing like that for the moment.

But 100% aggree for the Pokedex

**Comment by spark942** [comment]
what does it show for : 

- Normal Own & Shiny Released/Evolved

**Comment by DanielMReed** [comment]
I think that each flag overrides the one above, IFIAK

**Comment by RichardPaulAstley** [comment]
This is exactly the goal.

8 > 7 > 6 > 5 > 4 > 3 > 2 > 1 > 0 in order of priorities

**Comment by RichardPaulAstley** [comment]
Done.
