### ISSUE TITLE
Chansey attacks

### ISSUE THREAD

**Issue by MHketbi** [RichardPaulAstley/richardpaulastley.github.io#5]
all chansey pokemons attack for 0 or 1 (very low) regardless if it is against me or with me.

i don't know if this is intended.

**Comment by RichardPaulAstley** [comment]
Hi

In fact, this is intended. The game works using the real base stats of Pokemon. But Chansey doesn't have any GOOD Attack stat (5 for physicial, 35 for special)

So editing ONLY her could be special. But could you try to exp her on a easy-xp area (Old Rod, Magikarp with low base stats too) and see what happens ?

Thanks

**Comment by RichardPaulAstley** [comment]
Just for information, I saw more closer the problem of Chansey with the help of an user with a level 100 one, and confirmed that the game was not using Special stats.

Fixed that, your Chansey can hit a little again !

Sorry for the trouble !
