### ISSUE TITLE
Suggestion: Mark a pokemon as already caught

### ISSUE THREAD

**Issue by InfinitySamurai** [RichardPaulAstley/richardpaulastley.github.io#69]
Have some indication that a pokemon has already been caught/already in party/already in pokedex

**Comment by InfinitySamurai** [comment]
Duplicate of #58. I still think it would be nice to have some quick indicator next to the pokemon you're currently fighting

**Comment by w-sanches** [comment]
👍 on the idea.
It would be nice to have like a small pokeball so we can see that pokemons are already caught while battling them:
![something like this](https://user-images.githubusercontent.com/1727723/70484319-41549680-1aca-11ea-8645-00ccfcf570fb.png)
