### ISSUE TITLE
Suggestion: Make certain checkboxes radios instead

### ISSUE THREAD

**Issue by Naynuza** [RichardPaulAstley/richardpaulastley.github.io#72]
You are able to have View Storage checked while Manage Team or View Pokedex are also checked, this can be solved by making them radio buttons like how the pokeballs are.
HTML:
`<input type="radio">`
JS:
`x.setAttribute("type", "radio");`

**Comment by RichardPaulAstley** [comment]
Hi ! 
I've thought I answered to that but seems not sorry.

I'll check that and see to fix that.

Thanks o/

**Comment by RichardPaulAstley** [comment]
Seems the Storage PR was really messy in the end, it still creates issues.
