### ISSUE TITLE
Kangashkan

### ISSUE THREAD

**Issue by khaldresh** [RichardPaulAstley/richardpaulastley.github.io#9]
Kangashkan is missing and can't be caught anywhere

**Comment by RichardPaulAstley** [comment]
Just checked, and i've deleted by mistake after some update on the Safari Zone. My bad.
Just pushed a commit to fix that, F5 in a few minutes !

Sorry !

**Comment by khaldresh** [comment]
and chansey might have too low base stats   as ... well  344  344   on lvl 94 is a bit low isn't it?
